import type { Metadata } from 'next';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import './globals.css';

import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { initTtag } from '@/i18n/server';
import { InitTtag } from '@/i18n/client';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface iProps {
  children: React.ReactNode;
  params: { locale: string };
}

export default async function PageLayout({ children, params }: iProps) {
  initTtag(params.locale);

  return (
    <html lang={params.locale}>
      <body>
        <InitTtag locale={params.locale} />
        <div className="content">
          <Navbar />

          <div>{children}</div>

          <Footer />
        </div>
      </body>
    </html>
  );
}
