import type { Metadata } from 'next';
import './globals.css';

import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { initTtag } from '@/i18n/server';
import { InitTtag } from '@/i18n/client';
import { getStrapi } from '@/utils/getStrapi';
import { API } from '@/constants/api';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface iProps {
  children: React.ReactNode;
  params: { locale: string };
}

export default async function RootLayout({ children, params }: iProps) {
  initTtag(params.locale);
  await getStrapi(API.EQUIPMENT_CATEGORIES);

  return (
    <html lang={params.locale}>
      <body>
        <InitTtag locale={params.locale} />
        <Navbar />

        <div className="content">{children}</div>

        <Footer />
      </body>
    </html>
  );
}
